- name: Check sestatus
  shell: sestatus | awk '{print $NF}'
  register: seout

- name: Disable SELINUX
  shell: "setenforce 0"
  when: seout.stdout != "disabled"

- name: Disable Firewall
  service:
        name: firewalld
        state: stopped
        enabled: no
